### ISSUE TITLE
XSync initialized with new in Tests

### ISSUE THREAD

**Issue by kihats** [antkorwin/xsync-example#1]
Hi. Thank you for such a wonderful tool for handling concurrency.  Been wondering for sometime how banks and trading platforms do it. 
Anywhoo, I did this in my tests

     @Test
        public void xsyncTest() {
            XSync<String> xSync = new XSync<>();

            NonAtomicInt variable = new NonAtomicInt(0);

            ExecutorService executorService = Executors.newFixedThreadPool(10);

            executorService.submit(() -> {
                System.out.println("First Thread started.");
                ... // The rest of the code here

Notice I didn't `@Autowire` `XSync`. When I execute the test, I get the following

_First Thread started.
Second Thread started_

Just wondering why `xSync.execute()` method doesn't work in such a case. But if I `@Autowire` it it does.

**Comment by antkorwin** [comment]
Hi!
Thank you for kind words! 

Can you show me a full source code of the failed test? I will be glad to help you if I can.

**Comment by kihats** [comment]
import com.antkorwin.xsync.XSync;
    import org.assertj.core.api.Assertions;
    import org.junit.Test;

    import java.util.concurrent.ExecutorService;
    import java.util.concurrent.Executors;

    public class MshopBackendApplicationTests {

        @Test
        public void xsyncTest() {
            XSync<String> xSync = new XSync<>();

            NonAtomicInt variable = new NonAtomicInt(0);

            ExecutorService executorService = Executors.newFixedThreadPool(10);

            executorService.submit(() -> {
                System.out.println("First Thread started.");
                xSync.execute(new String("123"), () -> {
                    System.out.println("First Thread took a lock");
                    try {
                        Thread.sleep(5);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    variable.increment();
                    System.out.println("First Thread released a lock");
                });
             });

            executorService.submit(() -> {
                 try {
                    Thread.sleep(1L);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                System.out.println("Second Thread started");
                xSync.execute("123", () -> {
                    System.out.println("Second Thread took a lock");

                    // Assert
                    Assertions.assertThat(variable.getValue()).isEqualTo(1);

                    try {
                        Thread.sleep(1L);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    variable.increment();
                    System.out.println("Second Thread released a lock");
                });
            });
        }

        public static class NonAtomicInt {

            private int value;

            public NonAtomicInt(int value) {
                this.value = value;
            }

            public void increment() {
                this.value++;
            }

            public int getValue() {
                return this.value;
            }
        }

    }

Here is the full source code. When I run this in my IDE (**Intellij** - right click then **Run 'xsyncTest()'**), `xSync.execute()` does not run (coz I expect 'First Thread took a lock' to be printed). But I've noticed it only happens if I don't add **@RunWith(SpringRunner.class)** and **@SpringBootTest** annotation on my class. Actually it's not coz I haven't `@Autowire`d it as I had reported earlier.

**Comment by antkorwin** [comment]
This happens because you start other threads by the ExecutorService and these threads wait on the XSync mutex to conquer the synchronization, but JUnit doesn't wait while another thread complete in your tests.

This test case successfully ended while reached the last line of the test code, but at this moment other threads may not be completed. If you put `Thread.sleep(1000)` at the end of your test code then you can trace the whole sequence from other threads:

```
First Thread started.
Second Thread started
First Thread took a lock
First Thread released a lock
Second Thread took a lock
Second Thread released a lock
```

Sure, for production code you need to use a more correct approach to wait for the ending of other threads.

By the way, a variant with the SpringRunner works fine because in this runner performs a lot of post-processing actions for the JUnit test, these required a little more time before the test ends and your code from other threads has time to complete. It's just a happy coincidence =)

**Comment by kihats** [comment]
Hahaha. How come I didn't think of that? In fact I always put this at the end of my code when using `ExecutorService`:

    while(!executor.isTerminated()) {
        Thread.sleep(500);
    }

**Comment by antkorwin** [comment]
I can suggest you look at the [Awaitility](https://github.com/awaitility/awaitility) library this is a beautiful and more flexible solution to wait for something in the test code. You can set a timeout for waiting and a duration between polling, e.t.c.
